spring:
    application:
        name: api-gateway
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8181/realms/e-commerce-app-realm

server:
    port: 9000

springdoc:
    swagger-ui:
        path: /swagger-ui/index.html
        urls:
            - name: product-service
              url: /aggregate/product-service/api-docs
            - name: order-service
              url: /aggregate/order-service/api-docs
            - name: inventory-service
              url: /aggregate/inventory-service/api-docs
    api-docs:
        path: /api-docs
