version: '4'
services:
    mongodb:
        image: mongo:7.0.9
        container_name: mongodb
        ports:
            - "27020:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: product_db
        volumes:
            -   mongo-data:/data/db

volumes:
    mongo-data: