spring:
    application:
        name: product-service
    data:
        mongodb:
            host: localhost
            port: 27020
            database: product_db
            username: root
            password: password
            authentication-database: admin

server:
    port: 8010