spring:
    application:
        name: product-service
    data:
        mongodb:
            host: localhost
            port: 27017
            database: ecommerce_db

server:
    port: 8010

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true

springdoc:
    swagger-ui:
        path: /swagger-ui/index.html
    api-docs:
        path: /api-docs