INSERT INTO recipes (name, description, imageUrl, ingredients, instructions) VALUES
('Spaghetti Bolognese',
 'A classic Italian dish with a meaty, tomato sauce.',
 'http://example.com/images/spaghetti-bolognese.jpg',
 'Spaghetti, ground beef, onion, garlic, tomato sauce, salt, pepper, olive oil',
 '1. Heat olive oil in a large pan over medium heat. Add onion and garlic and cook until soft. 2. Add ground beef and cook until browned. 3. Add tomato sauce, salt, and pepper. Simmer for 20 minutes. 4. Cook spaghetti according to package instructions. 5. Serve spaghetti with meat sauce on top.'),
('Chicken Tikka Masala',
 'A popular Indian dish made with roasted chicken chunks in a spicy sauce.',
 'http://example.com/images/chicken-tikka-masala.jpg',
 'Chicken, yogurt, lemon juice, garlic, ginger, garam masala, cumin, paprika, coriander, turmeric, cayenne pepper, salt, pepper, tomato sauce, cream',
 '1. Marinate chicken in yogurt, lemon juice, garlic, ginger, garam masala, cumin, paprika, coriander, turmeric, cayenne pepper, salt, and pepper. 2. Roast chicken in the oven. 3. Simmer tomato sauce and cream. 4. Add chicken to sauce and serve with rice or naan.'),
('Beef Tacos',
 'A traditional Mexican dish consisting of a corn or wheat tortilla folded or rolled around a filling.',
 'http://example.com/images/beef-tacos.jpg',
 'Ground beef, onion, garlic, chili powder, cumin, paprika, salt, pepper, tortillas, lettuce, tomato, cheese, sour cream',
 '1. Cook ground beef with onion, garlic, chili powder, cumin, paprika, salt, and pepper. 2. Warm tortillas in a pan. 3. Assemble tacos with beef, lettuce, tomato, cheese, and sour cream.'),
('Sushi',
 'A traditional Japanese dish of prepared vinegared rice, usually with some sugar and salt, accompanying a variety of ingredients.',
 'http://example.com/images/sushi.jpg',
 'Rice, vinegar, sugar, salt, fish, vegetables, seaweed, soy sauce, wasabi, pickled ginger',
 '1. Cook rice and season with vinegar, sugar, and salt. 2. Prepare fish and vegetables. 3. Lay out seaweed and rice. 4. Add fish and vegetables. 5. Roll up and cut into pieces. 6. Serve with soy sauce, wasabi, and pickled ginger.');
