DROP TABLE IF EXISTS recipes;

CREATE TABLE recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description TEXT,
    imageUrl VARCHAR(255),
    ingredients TEXT,
    instructions TEXT
);