spring:
    application:
        name: quiz-app-monolithic
    datasource:
        url: jdbc:h2:mem:quiz_db
        driver-class-name: org.h2.Driver
        username: sa
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
    sql:
        init:
            mode: always
    h2:
        console:
            enabled: true
            path: /h2-console
